// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Infrastructure.Persistence;

#nullable disable

namespace TodoApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TodoAppDbContext))]
    [Migration("20260704152543_AddTaskActivityActor")]
    partial class AddTaskActivityActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TaskDependencies", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependencyId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("TaskDependencies", (string)null);
                });

            modelBuilder.Entity("TodoApp.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("TodoApp.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EffortEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DueDate");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TodoApp.Infrastructure.Persistence.TaskActivity", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("TaskId", "OccurredAt");

                    b.ToTable("TaskActivities", (string)null);
                });

            modelBuilder.Entity("TaskDependencies", b =>
                {
                    b.HasOne("TodoApp.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoApp.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApp.Domain.Tasks.TaskItem", b =>
                {
                    b.HasOne("TodoApp.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TodoApp.Domain.Tasks.PlanningFactors", "_planningFactors", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BusinessValue")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BusinessValue");

                            b1.Property<int>("EffortEstimate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PlanningEffort");

                            b1.Property<int>("RiskReduction")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RiskReduction");

                            b1.Property<int>("Urgency")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Urgency");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TodoApp.Domain.Tasks.PriorityScore", "_priority", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Band")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PriorityBand");

                            b1.Property<int>("BusinessValueContribution")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BusinessValueContribution");

                            b1.Property<int>("RiskReductionContribution")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RiskReductionContribution");

                            b1.Property<int>("UrgencyContribution")
                                .HasColumnType("INTEGER")
                                .HasColumnName("UrgencyContribution");

                            b1.Property<decimal>("Value")
                                .HasPrecision(10, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("PriorityScore");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("_planningFactors");

                    b.Navigation("_priority");
                });

            modelBuilder.Entity("TodoApp.Infrastructure.Persistence.TaskActivity", b =>
                {
                    b.HasOne("TodoApp.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
